baseURL = 'https://loop0.sh/'
languageCode = 'en-us'
title = 'loop0'
theme = "unix"
pagination.pagerSize = 5
pluralizelisttitles = false

[markup.goldmark.renderer]
unsafe= true


[params]
    github_url = "https://github.com/loop0"
    mastodon_url = "https://freeradical.zone/@loop0"


[taxonomies]
    series = 'series'
    tags = 'tags'